spring:

  profiles:
    include: jwt

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/demo
    username: sa
    password: 1

  data:
    web:
      pageable:
        default-page-size: 20  #페이징 할 때 기본값, 20개씩 조회

  servlet:
    multipart:
      max-request-size: 5MB  #업로드 파일 크기 총량 제한
      max-file-size: 2MB     #업로드 파일 크기 제한


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        user_sql_cooments: true

        default_batch_fetch_size: 100

    hibernate:
      ddl-auto: create

    open-in-view: false

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

      hiberante:
        SQL: debug

    boardexample:
      myboard: info

file:
  dir: C:\dongurami\file